export const RIDE_STRINGS = {
  home: {
    group: 'Group',
    groupDescription: 'Book more than 1 driver',
    saveDriver: 'Save Driver',
    saveDriverDescription: 'Choose your driver',
    searchPlaceholder: 'Where are you going',
    recentlyVisited: 'Recently Visited',
    seeAll: 'See All',
    moreDetails: 'More Details',
  },
  booking: {
    selectLocation: 'Select pickup location',
    searchLocationPlaceholder: 'Search location',
    selectMap: 'Select on map',
    selectCar: 'Selected cars',
    selected: 'Selected',
    addCar: 'Add your car +',
    selectSlot: 'Select your slot',
    startTime: 'Start Time',
    endTime: 'End Time',
    checkout: 'Checkout',
    total: 'Total',
    proceed: 'Proceed',
    paymentTitle: 'Payment mode',
    payment: 'Choose payment method',
    cash: 'Pay cash',
    upi: 'UPI',
    card: 'Debit or credit card',
    savedCard: 'Saved card',
    success: 'Payment Successful',
    successDescription:
      'Thank you! Your payment is successful!\n\nOur team will reach out shortly if required.',
    failure: 'Payment Error',
    failureDescription: 'Please try again',
    continue: 'Continue',
  },
  bookingDetail: {
    completed: 'Completed',
    upcoming: 'Upcoming',
    rebook: 'Re-book',
    moreDetails: 'More details',
    detail: 'Details',
    rideCharge: 'Ride Charge',
    insurance: 'Insurance',
    platformFee: 'Platform Fee',
    total: 'Total',
    reportAnIssue: 'Report an issue',
    overChargedDriver: 'Overcharged by the driver',
    rideSafety: 'Ride safety',
    billingRelatedIssues: 'Billing related issues',
    iWantToReport: 'I want to report the issue about the driver',
    cancelRide: 'Cancel Ride',
    driverNotAvailable: 'Sorry no driver is available right now',
    status: {
      completed: 'Completed',
      cancelled: 'Cancelled',
      alloted: 'Alloted',
      notAlloted: 'Not-Alloted',
    },
    modal: {
      cancellation: {
        title: 'Confirm cancellation?',
        message: 'Your locking fee will not be refunded',
        yesCancel: 'Yes, I want to cancel',
        back: 'Go Back',
        reasons: [
          'Overcharged by the driver',
          'False information',
          'Caused Accident',
          'Billing Related issues',
        ],
      },
      suggestion: {
        title: 'Is there something we could’ve done better?',
        message: 'Share your reason (optional)...',
        submit: 'Submit',
      },
      success: {
        title: 'You have successfully booked the driver.',
      },
      fail: {
        title: 'Booking Failed.',
      },
      somethingWentWrong: {
        title: 'Oops! Something went wrong!',
        message:
          'We encountered a technical error just now. Please try again in a minute.',
        tryAgain: 'Try again',
      },
      contact: {
        title: 'Thank you for contacting us',
        message: 'We will reach out to you shortly!',
        back: 'Go back',
      },
    },
  },
  savedLocation: {
    title: 'Saved Locations',
    addNewLocation: '+ Add new location',
  },
  savedDriver: {
    title: 'Saved Drivers',
    addNewLocation: '+ Add new driver',
  },
  driverDetail: {
    title: 'Driver Detail',
    about: 'About',
    phone: 'Phone',
    rides: 'Rides',
    experience: 'Experience',
    language: 'Language',
    gender: 'Gender',
    age: 'Age',
    pinCode: 'Pin code',
    address: 'Address',
    accidents: 'Accidents',
    status: {
      available: 'Available',
      notAvailable: 'Not Available',
    },
  },
  review: {
    title: 'Review',
    skip: 'Skip',
    yes: 'Yes',
    no: 'No',
    question1: 'Would you like to favorite this trip ?',
    question2: 'This is the average rating of this driver, do you agree ?',
    question3: 'Would you like to favorite this driver ?',
    describeExperience: 'Describe your experience....',
    goodSecurity: 'Good Security',
    fair: 'Fair',
    medium: 'Medium',
    finish: 'Finish',
  },
  report: {
    title: 'Report',
    skip: 'Skip',
    chooseReason: 'Choose your reason',
    reasons: [
      'Overcharged by the driver',
      'False information',
      'Caused Accident',
      'Billing Related issues',
    ],
    describeIssue: 'Describe your issue....',
    uploadPictures: 'Please upload pictures of your car if necessary',
    report: 'Report',
  },
};
